### ISSUE TITLE
Estilo do botão

### ISSUE THREAD

**Issue by iamtchelo** [vitormalencar/lightning#1]
Acho que você não deve usar propriedade que afeta o comportamento do botão, como a margin. Isso pode quebrar o layout e causar efeitos inesperados.

Faz mais sentido adicionar essas propriedades na aplicação que usa esse botão.

Dado que o botão é um styled-component, eu consigo adicionar mais estilo.

```js
import Button from 'lib';

const MyButton = styled(Button)`
  margin: 1em;
`
```

**Comment by vitormalencar** [comment]
thanks for the feedback 
I include this modification on the latest commit
